### ISSUE TITLE
Move Surah description to the top /  style surah title

### ISSUE THREAD

**Issue by asepkoswara** [ndeztea/QuranNote#21]
![screen shot 2016-03-09 at 11 00 38 am](https://cloud.githubusercontent.com/assets/6847652/13625275/9945366c-e5e8-11e5-83e9-975cad6fcbe8.png)

then move it to the right, aligned with title.

**Comment by ndeztea** [comment]
ieu mah head surah beda jeung nu di luhur, nu diluhur mah head search na

**Comment by ndeztea** [comment]
stylkeun..
