### ISSUE TITLE
design modal "mari berbagi"

### ISSUE THREAD

**Issue by ndeztea** [ndeztea/QuranNote#6]
improve this and make it better

![screen shot 2016-02-25 at 5 33 03 pm](https://cloud.githubusercontent.com/assets/5906480/13317133/4ab95e12-dbe6-11e5-8cf6-4fe0f6895a11.png)

**Comment by asepkoswara** [comment]
@ndeztea Please add class to each modal accordingly.

**Comment by ndeztea** [comment]
what class?
